---
# Playbook to create CIS hardened RHEL image on Azure
- name: Create Azure Resources
  hosts: localhost
  connection: local
  tasks:
    - name: Unpack SSH Private key
      copy:
        content: "{{ vault_ssh_private_key_data }}"
        dest: "{{ playbook_dir }}/{{ vault_ssh_private_key_name }}"
        mode: "0600"

    - name: "Create the Azure VPC"
      include_role:
        name: azureVpc
      vars:
        state: present

    - name: "Create Provisioner VM"
      include_role:
        name: azureVm
      vars:
        state: present
        public_ip: "{{ hostvars[vm].public_ip }}"
        security_group: "{{ hostvars[vm].security_group }}"
        nic: "{{ hostvars[vm].nic }}"
        flavor: "{{ hostvars[vm].flavor }}"
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        azure_image: "{{ hostvars[vm].azure_image }}"
      loop: "{{ groups['cloud'] }}"
      loop_control:
        loop_var: vm
        label: "Creating cloud VM {{ hostvars[vm].inventory_hostname }}"
      register: vm_output

    - name: Set Fact
      set_fact:
        ip_address: "{{ output_ip_address.state.ip_address }}"

    - name: Add the new Azure host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> ~/.ssh/known_hosts"

- name: Create Custom Image
  hosts: provisioner
  become: yes
  vars:
    ansible_host: "{{ hostvars['localhost'].ip_address }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ vault_ssh_private_key_name }}"
    ansible_user: "{{ vault_admin_user }}"
  roles:
    - rhelSubscriptionManagementSetup
    - rhelImageBuilderSetup
    - rhelBlueprintCreate
  tasks:
    - name: "Complete"
      debug:
        msg: "Complete"

...
