---
# Playbook to create CIS hardened RHEL image on Azure
# If re-running to generate an image add --skip-tags install to ansible-playbook command
- name: Create Azure Resources
  hosts: localhost
  connection: local
  tasks:
    - name: Unpack SSH Private key
      copy:
        content: "{{ vault_ssh_private_key_data }}"
        dest: "{{ playbook_dir }}/{{ vault_ssh_private_key_name }}"
        mode: "0600"
      tags:
        - install

    - name: "Create the Azure VPC"
      include_role:
        name: azureVpc
      vars:
        state: present
        azure_subscription_id: "{{ vault_azure_subscription_id }}"
        azure_client_id: "{{ vault_azure_client_id }}"
        azure_secret: "{{ vault_azure_secret }}"
        azure_tenant: "{{ vault_azure_tenant }}"
        resource_group: "{{ site_resource_group }}"
        azure_region: "{{ site_azure_region }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        subnet_cidr: "{{ site_subnet_cidr }}"
        supernet_cidr: "{{ site_supernet_cidr }}"
        virtual_network: "{{ site_virtual_network }}"
      tags:
        - install

    - name: "Create Provisioner VM"
      include_role:
        name: azureVm
      vars:
        state: present
        azure_subscription_id: "{{ vault_azure_subscription_id }}"
        azure_client_id: "{{ vault_azure_client_id }}"
        azure_secret: "{{ vault_azure_secret }}"
        azure_tenant: "{{ vault_azure_tenant }}"
        resource_group: "{{ site_resource_group }}"
        public_ip: "{{ hostvars[vm].public_ip }}"
        security_group: "{{ hostvars[vm].security_group }}"
        security_group_rules: "{{ hostvars[vm].security_group_rules }}"
        nic: "{{ hostvars[vm].nic }}"
        flavor: "{{ hostvars[vm].flavor }}"
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        azure_image: "{{ hostvars[vm].azure_image }}"
        virtual_network: "{{ site_virtual_network }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        azure_region: "{{ site_azure_region }}"
        admin_user: "{{ vault_admin_user }}"
        admin_pass: "{{ vault_admin_pass }}"
        os_disk_size: "{{ hostvars[vm].os_disk_size }}"
        ssh_public_key_data: "{{ vault_ssh_public_key_data }}"
      loop:
        - provisioner
      loop_control:
        loop_var: vm
        label: "Creating cloud VM {{ hostvars[vm].inventory_hostname }}"

    - name: Set Fact
      set_fact:
        ip_address: "{{ output_ip_address.state.ip_address }}"

    - name: Add the new Azure host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> ~/.ssh/known_hosts"

- name: Create Custom Image
  hosts: provisioner
  gather_facts: no
  become: yes
  vars:
    ansible_host: "{{ hostvars['localhost'].ip_address }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ vault_ssh_private_key_name }}"
    ansible_user: "{{ vault_admin_user }}"
  tasks:

    - name: Activate the RHEL subscription
      include_role:
        name: rhelSubscriptionManagementSetup
      vars:
        rhel_username: "{{ vault_rhel_subscription_username }}"
        rhel_password: "{{ vault_rhel_subscription_password }}"
      tags:
        - install

    - name: Prepare osbuild-composer to generate a SAP image
      include_role:
        name: rhelImageBuilderSetup
      tags:
        - install

    - name: Create the cloud image
      include_role:
        name: rhelBlueprintCreate
      vars:
        image_name: "{{ site_image_name }}"
        image_format: "{{ site_image_format }}"
        rawimage_dest: "{{ host_rawimage_dest }}"

    - name: Customise the cloud image
      include_role:
        name: rhelImageCustomisation
      vars:
        image_name: "{{ site_image_name }}"
        image_format: "{{ site_image_format }}"
        image_dest: "{{ host_rawimage_dest }}"
        ssh_public_key_name: "{{ vault_ssh_public_key_name }}"
        ssh_public_key_data: "{{ vault_ssh_public_key_data }}"

    - name: Customise the cloud image
      include_role:
        name: azureUploadImage
      vars:
        azure_subscription_id: "{{ vault_azure_subscription_id }}"
        azure_client_id: "{{ vault_azure_client_id }}"
        azure_secret: "{{ vault_azure_secret }}"
        azure_tenant: "{{ vault_azure_tenant }}"
        resource_group: "{{ site_resource_group }}"
        storage_account: "{{ site_storage_account }}"
        storage_container: "{{ site_storage_container }}"
        image_name: "{{ site_image_name }}"
        image_URI: "{{ host_image_URI }}"
        image_format: "{{ site_image_format }}"
        image_src: "{{ host_rawimage_dest }}"

- name: Create Azure VM with new image
  hosts: localhost
  connection: local
  tasks:

    - name: "Create Azure SAP Provisioning VM"
      include_role:
        name: azureVm
      vars:
        state: present
        azure_subscription_id: "{{ vault_azure_subscription_id }}"
        azure_client_id: "{{ vault_azure_client_id }}"
        azure_secret: "{{ vault_azure_secret }}"
        azure_tenant: "{{ vault_azure_tenant }}"
        resource_group: "{{ site_resource_group }}"
        public_ip: "{{ hostvars[vm].public_ip }}"
        security_group: "{{ hostvars[vm].security_group }}"
        security_group_rules: "{{ hostvars[vm].security_group_rules }}"
        nic: "{{ hostvars[vm].nic }}"
        flavor: "{{ hostvars[vm].flavor }}"
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        azure_image: "{{ hostvars[vm].azure_image }}"
        virtual_network: "{{ site_virtual_network }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        azure_region: "{{ site_azure_region }}"
        admin_user: "{{ vault_admin_user }}"
        admin_pass: "{{ vault_admin_pass }}"
        os_disk_size: "{{ hostvars[vm].os_disk_size }}"
        ssh_public_key_data: "{{ vault_ssh_public_key_data }}"
      loop: "{{ groups['azureimage'] }}"
      loop_control:
        loop_var: vm
        label: "Creating cloud VM {{ hostvars[vm].inventory_hostname }}"

    - name: Set Fact
      set_fact:
        ip_address: "{{ output_ip_address.state.ip_address }}"

    - name: Add the new Azure host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> ~/.ssh/known_hosts"

- name: Create Custom Image
  hosts: azureimage
  become: yes
  vars:
    ansible_host: "{{ hostvars['localhost'].ip_address }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ vault_ssh_private_key_name }}"
    ansible_user: "{{ vault_admin_user }}"
  tasks:
    - name: "Provision SAP HANA System Replication with HA on Azure"
      shell:
        cmd: "ansible-playbook site.yml"
        chdir: /saphana_deploument

# TODO: Apply hardening: https://github.com/rediculum/RHEL8_Lockdown
# TODO: Apply hardening via ansible: https://github.com/ansible-lockdown/RHEL8-CIS
# TODO: Connect to the remote server and execute site.yml
# TODO: Add Teardown for SAP HANA System

...
