---
# Playbook to destroy CIS hardened RHEL image on Azure
- name: Destroy Azure Environment
  hosts: localhost
  connection: local
  tasks:
    - name: "Destroy Provisioner VM"
      include_role:
        name: azureVm
      vars:
        state: absent
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        security_group: "{{ hostvars[vm].security_group }}"
        public_ip: "{{ hostvars[vm].public_ip }}"
      loop: "{{ groups['cloud'] }}"
      loop_control:
        loop_var: vm
        label: "Destroying cloud VM {{ hostvars[vm].inventory_hostname }}"
      register: vm_output

    - name: "Remove Azure Components"
      include_role:
        name: azureVpc
      vars:
        state: absent
        resource_group: "{{ site_resource_group }}"
        azure_region: "{{ site_azure_region }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        subnet_cidr: "{{ site_subnet_cidr }}"
        supernet_cidr: "{{ site_supernet_cidr }}"
        virtual_network: "{{ site_virtual_network }}"

...
