---
# Playbook to destroy CIS hardened RHEL image on Azure
- name: Destroy Azure Environment
  hosts: localhost
  connection: local
  tasks:
    - name: "Destroy Provisioner VM"
      include_role:
        name: azureVm
      vars:
        state: absent
        resource_group: "{{ site_resource_group }}"
        public_ip: "{{ hostvars[vm].public_ip }}"
        security_group: "{{ hostvars[vm].security_group }}"
        security_group_rules: "{{ hostvars[vm].security_group_rules }}"
        nic: "{{ hostvars[vm].nic }}"
        flavor: "{{ hostvars[vm].flavor }}"
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        azure_image: "{{ hostvars[vm].azure_image }}"
        virtual_network: "{{ site_virtual_network }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        azure_region: "{{ site_azure_region }}"
        admin_user: "{{ vault_admin_user }}"
        admin_pass: "{{ vault_admin_pass }}"
        ssh_key_public_data: "{{ vault_ssh_key_public_data }}"
      loop: "{{ groups['cloud'] }}"
      loop_control:
        loop_var: vm
        label: "Destroying cloud VM {{ hostvars[vm].inventory_hostname }}"
      register: vm_output

    - name: "Remove Azure Components"
      include_role:
        name: azureVpc
      vars:
        state: absent
        resource_group: "{{ site_resource_group }}"
        azure_region: "{{ site_azure_region }}"
        virtual_network_subnet: "{{ site_virtual_network_subnet }}"
        subnet_cidr: "{{ site_subnet_cidr }}"
        supernet_cidr: "{{ site_supernet_cidr }}"
        virtual_network: "{{ site_virtual_network }}"

# TODO: Remove storage container and storage blob

...
