---
# Playbook to destroy CIS hardened RHEL image on Azure
- name: Destroy Azure Environment
  hosts: localhost
  connection: local
  tasks:
    - name: "Destroy Provisioner VM"
      include_role:
        name: azureVm
      vars:
        state: absent
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        security_group: "{{ hostvars[vm].security_group }}"
        public_ip: "{{ hostvars[vm].public_ip }}"
      loop: "{{ groups['cloud'] }}"
      loop_control:
        loop_var: vm
        label: "Destroying cloud VM {{ hostvars[vm].inventory_hostname }}"
      register: vm_output

    - name: "Remove Azure Components"
      include_role:
        name: azureVpc
      vars:
        state: absent
...
