---

- name: Delete VM
  azure_rm_virtualmachine:
    resource_group: "{{ site_resource_group }}"
    name: "{{ vmname }}"
    state: absent
    remove_on_absent:
      - all

# TODO: Add location
- name: Delete an availability set for managed disk vm
  azure_rm_availabilityset:
    name: "{{ vmname }}-avs-managed-disk"
    resource_group: "{{ site_resource_group }}"
    state: absent

- name: Delete Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ site_resource_group }}"
    name: "{{ security_group }}"
    state: absent

- name: Delete public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ site_resource_group }}"
    name: "{{ public_ip }}"
    state: absent

...
