---
# Inventory variables added to all hosts
# All variables are prefixed with site_ to denote they belong to all hosts.
site_resource_group: azure-rhel-cis
site_storage_account: "{{ site_resource_group | replace('-', '') }}stacc"
site_storage_container: "{{ site_resource_group | replace('-', '') }}stcont"
site_image_name: "{{ site_resource_group }}-master-image"
site_image_format: "vhd"
site_virtual_network: "{{ site_resource_group }}-vnet1"
site_virtual_network_subnet: "{{ site_resource_group }}-vnet1-subnet1"
site_supernet_cidr: "10.10.0.0/22"
site_subnet_cidr: "10.10.0.0/24"
site_azure_region: uksouth

...
