---
# Main task file for rhelImageCustomisation
# Variables are prefixed with rhic_

- name: "Install dependent packages"
  yum:
    name: "{{ pkg.name }}"
    state: "{{ pkg.state }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: pkg
    label: "Installing {{ pkg.name }}"
  tags:
    - install

- name: Enable the cockpit socket
  service:
    name: libvird.service
    state: started
    enabled: yes

- name: Create tempdir
  tempfile:
    state: directory
  register: rhic_tempdir

- name: Copy the run_on_bootstrap.sh script to the tempdir
  copy:
    src: "run_on_bootstrap.sh"
    dest: "{{ rhic_tempdir.path }}"
    mode: "0777"

# TODO: Don't assume to use /root/
- name: Unpack SSH Private key
  copy:
    content: "{{ ssh_public_key_data }}"
    dest: "/root/.ssh/{{ ssh_public_key_name }}"
    mode: "0600"

# TODO: Take password from vault
# TODO: Take alternate ssh key from vault (or generate a new one - preferably not RSA!)
# TODO: Take hostname from configuration
# TODO: Don't assume to use /root/
- name: Embed the first boot script into the VHD image
  shell:
    cmd: >-
      export LIBGUESTFS_BACKEND=direct;
      virt-customize -a {{ image_dest }}
      --firstboot {{ rhic_tempdir.path }}/run_on_bootstrap.sh
      --root-password "password:redhat"
      --hostname bootstrap
      --ssh-inject root:file:/root/.ssh/{{ ssh_public_key_name }}
      --selinux-relabel

- name: Remove tempdir
  file:
    path: "{{ rhic_temp.path }}"
    state: absent

...
