---
packages:
  - name: qemu-kvm
    state: latest

  - name: libvirt
    state: latest

  - name: python3-libvirt
    state: latest

  - name: libguestfs-tools
    state: latest

  - name: virt-install
    state: latest
...
