---
# Main tasks file for rhelBlueprintCreate role
# Variables are prefixed with "rhbc_"

- name: Create tempdir
  tempfile:
    state: directory
    suffix: blueprint
  register: rhbc_temp

- name: Create blueprint.toml
  template:
    src: blueprint.toml.j2
    dest: "{{ rhbc_temp.path }}/{{ image_name }}.toml"

- name: "Push blueprint {{ image_name }} to the ImageBuilder"
  shell: composer-cli blueprints push "{{ rhbc_temp.path }}/{{ image_name }}.toml"

- name: "Solve package dependencies for {{ image_name }}"
  shell: composer-cli blueprints depsolve "{{ image_name }}"

# TODO: add azure.toml at end of the shell command, this will allow the image to be uploaded to Azure
#
#provider = "azure"
#[settings]
#storageAccount = "your storage account name"
#storageAccessKey = "storage access key you copied in the Azure portal"
#container = "your storage container name"
#
- name: Create the the VM image
  shell: "composer-cli compose start {{ image_name }} {{ image_format }}"

# TODO: Poll command and wait until it is finished before proceeding
- name: Wait for image to be created
  shell: composer-cli compose status
  async: "1200"
  poll: "05"
  register: rhbc_image_create

#- name: "Debug"
#  debug:
#    var: rhbc_image_create

- name: Check on status of async task to build image
  async_status:
    jid: "{{ rhbc_image_create.ansible_job_id }}"
  register: job_result
  until: "'FINISHED' in rhbc_image_create.stdout"
  retries: 100
  delay: 10

# TODO: Get the image uuid

...
