---

- name: Restart osbuild-composer service
  service:
    name: osbuild-composer.service
    state: restarted
  listen: "restart osbuild-composer"

- name: Restart osbuild-worker service
  service:
    name: osbuild-worker@1.service
    state: restarted
  listen: "restart osbuild-composer"
...
