---

- name: Restart osbuild-composer service
  service:
    name: osbuild-composer.service
    state: restarted
  listen: "restart osbuild-composer"

- name: Restart osbuild-worker@ service.d
  service:
    name: osbuild-worker@.service.d
    state: restarted
  listen: "restart osbuild-composer"

- name: Restart osbuild-worker@ service
  service:
    name: osbuild-worker@1.service
    state: restarted
  listen: "restart osbuild-composer"

...
