---
# Playbook to create CIS hardened RHEL image on Azure
- name: Create Azure Environment
  hosts: localhost
  connection: local
  tasks:

    - name: "Setup Azure Tasks"
      include_tasks: "{{ item }}"
      loop:
        - ../tasks/create_resource_group.yml
        - ../tasks/create_virtual_network.yml
        - ../tasks/create_subnet.yml

# TODO: Possibly loop over hostvars['provisioners']
    - name: "Create Provisioner VM"
      include_tasks: ../tasks/create_vm.yml
      vars:
        public_ip: "{{ hostvars[vm].public_ip }}"
        security_group: "{{ hostvars[vm].security_group }}"
        nic: "{{ hostvars[vm].nic }}"
        flavor: "{{ hostvars[vm].flavor }}"
        vmname: "{{ hostvars[vm].inventory_hostname }}"
        azure_image: "{{ hostvars[vm].azure_image }}"
      loop: "{{ groups['cloud'] }}"
      loop_control:
        loop_var: vm
        label: "Creating cloud VM {{ hostvars[vm].inventory_hostname }}"
      register: vm_output

    - name: Set Fact
      set_fact:
        ip_address: "{{ output_ip_address.state.ip_address }}"
# TODO: Get provisioner IP address
# TODO: Update Ansible variable to use public IP
# TODO: Update Ansible to use correct SSH key

- name: Create Custom Image
  hosts: provisioner
  become: yes
  vars:
    ansible_host: "{{ hostvars['localhost'].ip_address }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/../id_rsa"
  tasks:
    - name: "Work on remote"
      debug:
        var: ansible_facts

    #- name: "Create Image"
    #  include_tasks: "{{ item }}"
    #  loop:
    #    - tasks/create_storage_container.yml
    #    - tasks/create_storage_blob.yml
    #    - tasks/create_image_from_vhd.yml

    - name: Exit
      fail:
        msg: "ERROR"

- name: Start VM instances using Custom Image
  hosts: provisioner
  become: yes
  tasks:

    - name: "Create Image"
      include_tasks: "{{ item }}"
      loop:
        - tasks/create_storage_container.yml
        - tasks/create_storage_blob.yml
...
