---
- name: Create a subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ virtual_network_subnet }}"
    address_prefix: "{{ subnet_cidr }}"
    virtual_network_name: "{{ virtual_network }}"
...
