---
- name: Create a subnet
  azure_rm_subnet:
    resource_group: "{{ site_resource_group }}"
    name: "{{ site_virtual_network_subnet }}"
    address_prefix: "{{ site_subnet_cidr }}"
    virtual_network_name: "{{ site_virtual_network }}"
...
