---
- name: Delete subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ virtual_network }}"
    name: "{{ virtual_network_subnet }}"
    state: absent
...
