---
# Main task file for the azureVm role

- block:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ public_ip }}"
      register: output_ip_address

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group }}"
        rules: "{{ security_group_rules }}"
      tags:
        - install

    - name: Create virtual network interface
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic }}"
        virtual_network: "{{ virtual_network }}"
        subnet: "{{ virtual_network_subnet }}"
        security_group: "{{ security_group }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: "{{ public_ip }}"
            primary: True
      tags:
        - install

    - name: Create an availability set for managed disk vm
      azure_rm_availabilityset:
        name: "{{ vmname }}-avs-managed-disk"
        resource_group: "{{ resource_group }}"
        platform_update_domain_count: 5
        platform_fault_domain_count: 2
        sku: Aligned
        location: "{{ azure_region }}"
      tags:
        - install

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vmname }}"
        vm_size: "{{ flavor }}"
        admin_username: "{{ admin_user }}"
        admin_password: "{{ admin_pass }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ admin_user }}/.ssh/authorized_keys"
            key_data: "{{ ssh_public_key_data }}"
        network_interfaces: "{{ nic }}"
        availability_set: "{{ vmname }}-avs-managed-disk"
        managed_disk_type: StandardSSD_LRS
        image: "{{ azure_image }}"
      tags:
        - install

    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  when: state == 'present'

- block:

    - name: Delete VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vmname }}"
        remove_on_absent: all
        state: absent

    - name: Delete an availability set for managed disk vm
      azure_rm_availabilityset:
        name: "{{ vmname }}-avs-managed-disk"
        resource_group: "{{ resource_group }}"
        state: absent

    - name: Delete Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ security_group }}"
        state: absent

    - name: Delete public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ public_ip }}"
        state: absent

  when: state == 'absent'

...
